# Generated by Django 4.0 on 2022-07-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_alter_employee_next_of_kin_relationship'),
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpdesk',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('issue_name', 'department')},
        ),
    ]
