# Generated by Django 4.0.7 on 2022-11-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_helpdesk_options_alter_issue_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='for_management',
            field=models.BooleanField(default=False),
        ),
    ]
