# Generated by Django 4.0.7 on 2022-12-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_user_is_applicant_user_is_normal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_applicant',
            field=models.BooleanField(default=False, help_text='tick if user is an applicant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_head',
            field=models.BooleanField(default=False, help_text='tick if user is HOD'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_normal_user',
            field=models.BooleanField(default=False, help_text='tick if user will not use help desk'),
        ),
    ]
