# Generated by Django 4.0.7 on 2022-11-20 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpdesk.models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_user_for_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdesk',
            name='handle_over_to',
            field=models.ForeignKey(blank=True, default=helpdesk.models.handle_over_to, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
