# Generated by Django 4.0.7 on 2022-12-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_alter_user_is_applicant_alter_user_is_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_applicant',
        ),
    ]
