# Generated by Django 4.0.7 on 2022-11-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_alter_helpdesk_handle_over_to'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
