# Generated by Django 4.0.7 on 2022-12-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_remove_user_is_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_normal_user',
            field=models.BooleanField(default=True, help_text='tick if user will not use help desk'),
        ),
    ]
