# Generated by Django 4.0.7 on 2022-11-26 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_alter_user_managers_alter_helpdesk_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdesk',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_users', to=settings.AUTH_USER_MODEL, verbose_name='Reported By'),
        ),
    ]
