# Generated by Django 4.0 on 2022-07-22 11:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hrms.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('sacked', 'SACKED'), ('resigned', 'RESIGNED')], default='active', max_length=10)),
                ('employee_id', models.CharField(blank=True, help_text='system generated (leave blank)', max_length=200, unique=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(choices=[('mr', 'MR'), ('mrs', 'MRS'), ('doc', 'DOCTOR'), ('prof', 'PROFESSOR'), ('miss', 'MISS'), ('sir', 'SIR'), ('hon', 'HONARABLE')], max_length=20, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('other_name', models.CharField(blank=True, max_length=50, verbose_name='Other Name(s)')),
                ('nia', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=125)),
                ('dob', models.DateField(help_text='Date Of Birth')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('date_employed', models.DateField(help_text='Date Of Employment', null=True)),
                ('address', models.CharField(help_text='Residential Address', max_length=100)),
                ('languages', models.CharField(max_length=200, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10)),
                ('snnit_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_merried', models.BooleanField(default=False)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ac', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Accont No.')),
                ('salary', models.CharField(blank=True, max_length=16, null=True)),
                ('emergency_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_phone', models.CharField(blank=True, help_text='emergency contact number', max_length=15, null=True)),
                ('emergency_address', models.CharField(blank=True, max_length=200, null=True)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=200, null=True)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('next_of_kin_address', models.CharField(blank=True, max_length=200, null=True)),
                ('next_of_kin_relationship', models.CharField(max_length=20, null=True)),
                ('emp_uiid', models.UUIDField(default=uuid.uuid4, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.designation')),
            ],
            options={
                'ordering': ('-updated_at',),
                'unique_together': {('first_name', 'last_name', 'mobile')},
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=70)),
                ('days', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('position', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=25)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('status', models.CharField(choices=[('approved', 'APPROVED'), ('unapproved', 'UNAPPROVED'), ('pending', 'PENDING')], default='pending', max_length=15)),
                ('phone', models.CharField(blank=True, help_text='phone while on leave', max_length=15, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/%Y-%m-%d')),
                ('collegue_approve', models.BooleanField(default=False)),
                ('line_manager', models.BooleanField(default=False)),
                ('hr_manager', models.BooleanField(default=False)),
                ('on_leave', models.BooleanField(default=False)),
                ('from_leave', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_employees', to='hrms.employee')),
                ('handle_over_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handler_over_to', to='hrms.employee')),
                ('policy', models.ForeignKey(help_text='Leave Policy', on_delete=django.db.models.deletion.CASCADE, to='hrms.leavepolicy')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentHeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee', models.ManyToManyField(blank=True, related_name='departart_heads', to='hrms.Employee')),
            ],
            options={
                'verbose_name': 'Department Head',
                'verbose_name_plural': 'Department Heads',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('first_in', models.TimeField()),
                ('last_out', models.TimeField(null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT'), ('UNAVAILABLE', 'UNAVAILABLE')], max_length=15)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionalMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hrms.employee')),
            ],
            options={
                'unique_together': {('name', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='PreviousEployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=200, null=True)),
                ('job_title', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='hrms.employee')),
            ],
            options={
                'unique_together': {('company', 'job_title')},
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('certificate', models.CharField(max_length=200)),
                ('date_completed', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='hrms.employee')),
            ],
            options={
                'unique_together': {('school_name', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=6, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('other_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Other Name(s)')),
                ('dob', models.DateField(null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarys', to='hrms.employee')),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
