# Generated by Django 4.0.7 on 2022-11-30 01:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hrms.partials
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BaseModel', '0001_initial'),
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snnit_amount', models.DecimalField(decimal_places=2, default=5.5, help_text='value in percentage eg 5.5%', max_digits=5)),
                ('snnit_amount_company', models.DecimalField(decimal_places=2, default=13, help_text='value in percentage eg 13%', max_digits=5, verbose_name='snnit amount rch')),
                ('provedent_amont', models.DecimalField(decimal_places=2, default=5, help_text='value in percentage eg 5%', max_digits=5)),
                ('provedent_amont_company', models.DecimalField(decimal_places=2, default=5, help_text='value in percentage eg 5%', max_digits=5, verbose_name='provedent amont rch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('sacked', 'SACKED'), ('resign', 'RESIGN')], default='active', max_length=10)),
                ('exit_check', models.BooleanField(default=False, help_text='checks to see if the employee exit checks are successful')),
                ('date_exited', models.DateField(blank=True, help_text='shows the date when the employee exited from the company', null=True)),
                ('employee_id', models.CharField(blank=True, help_text='system generated (leave blank)', max_length=200, null=True, unique=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(choices=[('mr', 'MR'), ('mrs', 'MRS'), ('doc', 'DOCTOR'), ('prof', 'PROFESSOR'), ('miss', 'MISS'), ('sir', 'SIR'), ('hon', 'HONARABLE')], max_length=20, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('other_name', models.CharField(blank=True, max_length=50, verbose_name='Other Name(s)')),
                ('is_head', models.BooleanField(default=False, verbose_name='HOD')),
                ('nia', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=125)),
                ('dob', models.DateField(help_text='Date Of Birth')),
                ('date_employed', models.DateField(help_text='Date Of Employment', null=True)),
                ('address', models.CharField(help_text='Residential Address', max_length=100)),
                ('languages', models.CharField(max_length=200, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10)),
                ('snnit_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_merried', models.CharField(blank=True, choices=[('married', 'MARRIED'), ('not_married', 'NOT MARRIED'), ('divorced', 'Divorced'), ('widow', 'WIDOW'), ('widower', 'WIDOWER')], max_length=20, null=True, verbose_name='marital_status')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ac', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Accont No.')),
                ('salary', models.CharField(blank=True, max_length=16, null=True)),
                ('emergency_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_phone', models.CharField(blank=True, help_text='emergency contact number', max_length=15, null=True)),
                ('emergency_address', models.CharField(blank=True, max_length=200, null=True)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=200, null=True)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('next_of_kin_address', models.CharField(blank=True, max_length=200, null=True)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_uiid', models.UUIDField(default=uuid.uuid4, null=True)),
                ('anviz_id', models.CharField(blank=True, max_length=20, null=True)),
                ('applicant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant', to='applicant.applicant')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_department', to='BaseModel.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseModel.designation')),
            ],
            options={
                'ordering': ('-updated_at',),
                'unique_together': {('employee_id', 'mobile')},
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=70)),
                ('days', models.PositiveSmallIntegerField(default=0)),
                ('has_days', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionalMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hrms.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousEployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=200, null=True)),
                ('job_title', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='hrms.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('certificate', models.CharField(max_length=200)),
                ('date_completed', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='hrms.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Documente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('file', models.FileField(null=True, upload_to='documents/%Y-%m-%d')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='hrms.employee')),
                ('filename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filenames', to='hrms.file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=6, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('other_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Other Name(s)')),
                ('dob', models.DateField(null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarys', to='hrms.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_number', models.IntegerField(default=hrms.partials.generated_ticket_number)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('status', models.CharField(choices=[('approved', 'APPROVED'), ('unapproved', 'UNAPPROVED'), ('pending', 'PENDING')], default='pending', max_length=15)),
                ('phone', models.CharField(blank=True, help_text='phone while on leave', max_length=15, null=True)),
                ('resuming_date', models.DateField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/%Y-%m-%d')),
                ('supervisor', models.BooleanField(default=False, verbose_name='supervisor')),
                ('line_manager', models.BooleanField(default=False, verbose_name='hod')),
                ('hr_manager', models.BooleanField(default=False)),
                ('on_leave', models.BooleanField(default=False)),
                ('from_leave', models.BooleanField(default=False)),
                ('leavedays', models.IntegerField(default=0)),
                ('supervisor_approval', models.JSONField(blank=True, default=dict, null=True)),
                ('line_manager_approval', models.JSONField(blank=True, default=dict, null=True)),
                ('hr_manager_approval', models.JSONField(blank=True, default=dict, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_employees', to='hrms.employee')),
                ('policy', models.ForeignKey(help_text='Leave Policy', on_delete=django.db.models.deletion.CASCADE, to='hrms.leavepolicy')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('employee', 'start')},
            },
        ),
    ]
