# Generated by Django 4.0 on 2022-07-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
