# Generated by Django 4.0.7 on 2022-12-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reason_exiting',
            field=models.TextField(blank=True, help_text='reason of exiting', null=True),
        ),
    ]
