# Generated by Django 4.0 on 2022-07-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_alter_employee_next_of_kin_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
