# Generated by Django 4.0.7 on 2022-12-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_employee_reason_exiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='leave/%Y-%m-%d'),
        ),
    ]
