# Generated by Django 4.0 on 2022-07-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_alter_employee_nia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('employee_id', 'mobile')},
        ),
    ]
