# Generated by Django 4.0 on 2022-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_alter_employee_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, help_text='system generated (leave blank)', max_length=200),
        ),
    ]
