# Generated by Django 4.0.7 on 2022-12-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_alter_employee_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('terminated', 'TERMINATED'), ('resigned', 'RESIGNED'), ('dismised', 'DISMISED'), ('redundancy', 'REDUNDANCY')], default='active', max_length=10),
        ),
    ]
