# Generated by Django 4.0 on 2022-07-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, help_text='system generated (leave blank)', max_length=200, unique=True),
        ),
    ]
