# Generated by Django 4.0.7 on 2022-12-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_alter_leave_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, help_text='system generated (leave blank)', max_length=200, null=True, unique=True),
        ),
    ]
