# Generated by Django 4.0 on 2022-07-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0007_designation_net_month_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='provedent_amont',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, help_text='value in percentage eg 5%', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='provedent_amont_company',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, help_text='value in percentage eg 5%', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='snnit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=5.5, help_text='value in percentage eg 5.5%', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='snnit_amount_company',
            field=models.DecimalField(blank=True, decimal_places=2, default=13, help_text='value in percentage eg 13%', max_digits=5, null=True),
        ),
    ]
