# Generated by Django 4.0.7 on 2022-12-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0007_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalmembership',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='memberships/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='documente',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start',
            field=models.DateField(db_index=True),
        ),
    ]
