# Generated by Django 4.0 on 2022-07-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0008_alter_designation_provedent_amont_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_header',
            field=models.BooleanField(default=False, verbose_name='HOD'),
        ),
    ]
