# Generated by Django 4.0 on 2022-07-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0009_employee_is_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_header',
            new_name='is_head',
        ),
    ]
