# Generated by Django 4.0.7 on 2022-12-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0009_dependant_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependant',
            name='is_beneficiary',
            field=models.BooleanField(default=False),
        ),
    ]
