# Generated by Django 4.0.7 on 2022-12-25 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_alter_applicant_options_and_more'),
        ('hrms', '0010_dependant_is_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='applicant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.applicant'),
        ),
    ]
