# Generated by Django 4.0 on 2022-07-28 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0011_alter_designation_reports_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='description',
        ),
    ]
