# Generated by Django 4.0.7 on 2023-01-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0014_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('terminated', 'TERMINATED'), ('resigned', 'RESIGNED'), ('dismised', 'DISMISED'), ('management', 'FOR MANAGEMENT')], default='active', max_length=10),
        ),
    ]
