# Generated by Django 4.0 on 2022-07-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0014_alter_contribution_provedent_amont_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='provedent_amont_company',
            field=models.DecimalField(decimal_places=2, default=5, help_text='value in percentage eg 5%', max_digits=5, verbose_name='provedent amont rch'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='snnit_amount_company',
            field=models.DecimalField(decimal_places=2, default=13, help_text='value in percentage eg 13%', max_digits=5, verbose_name='snnit amount rch'),
        ),
    ]
