# Generated by Django 4.0 on 2022-08-03 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0014_applicant_address'),
        ('hrms', '0015_alter_contribution_provedent_amont_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='applcant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.applicant'),
        ),
    ]
