# Generated by Django 4.0.7 on 2023-01-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0016_employeeexit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeexit',
            old_name='name',
            new_name='data',
        ),
    ]
