# Generated by Django 4.0 on 2022-08-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0016_employee_applcant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='applcant',
            new_name='applicant',
        ),
    ]
