# Generated by Django 4.0 on 2022-08-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0017_rename_applcant_employee_applicant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='education',
            unique_together=set(),
        ),
    ]
