# Generated by Django 4.0.7 on 2023-01-11 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0017_rename_name_employeeexit_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
    ]
