# Generated by Django 4.0.7 on 2023-01-12 01:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0018_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_uiid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('terminated', 'TERMINATED'), ('resigned', 'RESIGNED'), ('dismised', 'DISMISED'), ('management', 'FOR MANAGEMENT')], db_index=True, default='active', max_length=10),
        ),
    ]
