# Generated by Django 4.0.7 on 2023-01-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0019_alter_employee_emp_uiid_alter_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'APPROVED'), ('unapproved', 'UNAPPROVED'), ('pending', 'PENDING')], default='pending', max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_changes', to='hrms.employee')),
            ],
        ),
    ]
