# Generated by Django 4.0 on 2022-08-03 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0014_applicant_address'),
        ('hrms', '0019_alter_dependant_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='applicant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant', to='applicant.applicant'),
        ),
    ]
