# Generated by Django 4.0.7 on 2023-01-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0020_requestchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='request_change',
            field=models.BooleanField(default=True),
        ),
    ]
