# Generated by Django 4.0.7 on 2023-01-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0021_employee_request_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='request_change',
            field=models.BooleanField(default=False),
        ),
    ]
