# Generated by Django 4.0 on 2022-08-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0021_remove_attendance_staff_delete_recruitment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='reports_to',
        ),
        migrations.AddField(
            model_name='designation',
            name='report_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_head': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_to', to='hrms.designation'),
        ),
    ]
