# Generated by Django 4.0.7 on 2022-09-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0023_requestchange_created_at_requestchange_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='request_change',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
