# Generated by Django 4.0 on 2022-08-10 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0024_alter_designation_report_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='report_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'pk': '<django.db.models.fields.related.ForeignKey>'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_to', to='hrms.designation'),
        ),
    ]
