# Generated by Django 4.0.7 on 2023-01-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0025_alter_employee_request_change_alter_leave_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='date_exited',
            new_name='date_departure',
        ),
    ]
