# Generated by Django 4.0.7 on 2023-01-18 00:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0026_rename_date_exited_employee_date_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestchange',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
