# Generated by Django 4.0 on 2022-08-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0026_alter_designation_report_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leavedays',
            field=models.IntegerField(default=0),
        ),
    ]
