# Generated by Django 3.2.16 on 2023-05-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0027_alter_requestchange_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('approved', 'APPROVED'), ('unapproved', 'UNAPPROVED'), ('pending', 'PENDING'), ('awaiting', 'AWAITING'), ('done', 'DONE')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='requestchange',
            name='status',
            field=models.CharField(choices=[('approved', 'APPROVED'), ('unapproved', 'UNAPPROVED'), ('pending', 'PENDING'), ('awaiting', 'AWAITING'), ('done', 'DONE')], default='pending', max_length=20),
        ),
    ]
