# Generated by Django 4.0.7 on 2022-09-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0029_alter_employee_is_merried'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('sacked', 'SACKED'), ('resign', 'Resign')], default='active', max_length=10),
        ),
    ]
