# Generated by Django 4.0.7 on 2022-09-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0031_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_merried',
            field=models.CharField(blank=True, choices=[('married', 'MARRIED'), ('not_married', 'NOT MARRIED'), ('divorced', 'Divorced'), ('widow', 'Widow'), ('widower', 'Widower')], max_length=20, null=True, verbose_name='marital_status'),
        ),
    ]
