# Generated by Django 4.0.7 on 2022-09-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0033_alter_employee_is_merried'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='handle_over_to',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handler_over_to', to='hrms.employee'),
        ),
    ]
