# Generated by Django 4.0.7 on 2022-09-17 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0034_alter_leave_handle_over_to'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='previouseployment',
            unique_together={('job_title', 'employee')},
        ),
    ]
