# Generated by Django 4.0.7 on 2022-10-03 22:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0036_alter_education_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Documente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('file', models.FileField(null=True, upload_to='documents/%Y-%m-%d')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='hrms.employee')),
                ('filename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filenames', to='hrms.file')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
