# Generated by Django 4.0.7 on 2022-10-12 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0038_alter_documente_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documente',
            name='filename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filenames', to='hrms.file'),
        ),
    ]
