# Generated by Django 4.0.7 on 2022-10-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0039_alter_documente_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='exit_check',
            field=models.BooleanField(default=False),
        ),
    ]
