# Generated by Django 4.0.7 on 2022-10-12 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0040_employee_exit_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_exited',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
