# Generated by Django 4.0.7 on 2022-10-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0041_employee_date_exited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_exited',
            field=models.DateField(blank=True, null=True),
        ),
    ]
