# Generated by Django 4.0.7 on 2022-10-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0042_alter_employee_date_exited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_exited',
            field=models.DateField(blank=True, help_text='shows the date when the employee exited from the company', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='exit_check',
            field=models.BooleanField(default=False, help_text='checks to see if the employee exit checks are successful'),
        ),
    ]
