# Generated by Django 4.0.7 on 2022-10-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0043_alter_employee_date_exited_alter_employee_exit_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='shortname',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
