# Generated by Django 4.0.7 on 2022-10-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0044_department_shortname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='reason',
        ),
        migrations.AddField(
            model_name='leave',
            name='resuming_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
