# Generated by Django 4.0.7 on 2022-11-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0046_remove_leave_handle_over_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='collegue_approve',
        ),
        migrations.AddField(
            model_name='leave',
            name='supervisor',
            field=models.BooleanField(default=False, verbose_name='supervisor'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='line_manager',
            field=models.BooleanField(default=False, verbose_name='hod'),
        ),
    ]
