# Generated by Django 4.0.7 on 2022-11-04 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0048_alter_leave_resuming_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leave',
            unique_together={('employee', 'start')},
        ),
    ]
