# Generated by Django 4.0.7 on 2022-11-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0049_alter_leave_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approvals',
            field=models.JSONField(null=True, verbose_name={'hr_manager': '', 'line_manager': '', 'supervisor': ''}),
        ),
    ]
