# Generated by Django 4.0.7 on 2022-11-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0051_alter_leave_approvals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approvals',
            field=models.JSONField(default={}),
        ),
    ]
