# Generated by Django 4.0.7 on 2022-11-10 03:32

from django.db import migrations, models
import hrms.partials


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0055_alter_leave_approvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_number',
            field=models.IntegerField(default=hrms.partials.generated_ticket_number),
        ),
    ]
