# Generated by Django 4.0.7 on 2022-11-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0056_leave_leave_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='has_days',
            field=models.BooleanField(default=True),
        ),
    ]
