# Generated by Django 4.0.7 on 2022-11-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0057_leavepolicy_has_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='for_management',
            field=models.BooleanField(default=False, help_text='employee for royalde management'),
        ),
    ]
