# Generated by Django 4.0.7 on 2022-11-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0058_employee_for_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='for_management',
            field=models.BooleanField(default=False),
        ),
    ]
