# Generated by Django 4.0.7 on 2022-11-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0059_department_for_management'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='approvals',
            new_name='hr_manager_approval',
        ),
        migrations.AddField(
            model_name='leave',
            name='line_manager_approval',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='supervisor_approval',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
