# Generated by Django 4.0.7 on 2022-11-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0060_rename_approvals_leave_hr_manager_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leavedays_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
