# Generated by Django 4.0.7 on 2022-11-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0063_leave_leavedays_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leavedays_counter',
        ),
    ]
