# Generated by Django 4.0.7 on 2022-11-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0064_remove_leave_leavedays_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavepolicy',
            name='days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
