# Generated by Django 4.0.7 on 2022-11-19 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0066_remove_employee_age_employee_exit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='exit_status',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_department', to='hrms.department'),
        ),
    ]
