# Generated by Django 4.0.7 on 2022-11-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0067_remove_employee_exit_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='for_management',
        ),
    ]
