# Generated by Django 4.0.7 on 2022-11-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0068_remove_employee_for_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='anviz_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
