# Generated by Django 4.0.7 on 2022-11-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0069_employee_anviz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, help_text='system generated (leave blank)', max_length=200, null=True, unique=True),
        ),
    ]
