# Generated by Django 4.0.7 on 2022-11-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0070_alter_employee_employee_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentHeads',
        ),
    ]
