# Generated by Django 4.0.7 on 2022-11-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0071_delete_departmentheads'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dependant',
            unique_together=set(),
        ),
    ]
