# Generated by Django 4.0.7 on 2022-11-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0072_alter_dependant_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='education',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='professionalmembership',
            unique_together=set(),
        ),
    ]
