# Generated by Django 4.0.7 on 2022-11-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0073_alter_education_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='previouseployment',
            unique_together=set(),
        ),
    ]
