# Generated by Django 4.0.7 on 2023-01-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseModel', '0002_alter_department_options_alter_designation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='anviz_department',
            field=models.PositiveSmallIntegerField(blank=True, help_text='ID from anviz department', null=True),
        ),
    ]
