# Generated by Django 4.0.7 on 2022-11-30 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BaseModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('other_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('selected', 'SELECTED'), ('not selected', 'NOT SELECTED'), ('in review', 'IN REVIEW')], default='in review', max_length=20)),
                ('cv', models.FileField(blank=True, null=True, upload_to='media/cv/%Y-%m-%d')),
                ('comment', models.TextField(blank=True, help_text='eg congratulations or wish them luck', null=True)),
                ('resuming_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('salary', models.CharField(blank=True, max_length=200, null=True, verbose_name='net month salary')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_department', to='BaseModel.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_designation', to='BaseModel.designation')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
