# Generated by Django 4.0 on 2022-07-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrms', '0006_alter_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('other_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('selected', 'SELECTED'), ('not selected', 'NOT SELECTED'), ('pending', 'PENDING')], default='pending', max_length=20)),
                ('cv', models.FileField(upload_to='media/cv/%Y-%m-%d')),
                ('comment', models.TextField(blank=True, help_text='Comment', null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.designation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
