# Generated by Django 4.0 on 2022-07-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='comment',
            field=models.TextField(blank=True, help_text='eg congratulations or wish them luck', null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('selected', 'SELECTED'), ('not selected', 'NOT SELECTED'), ('in review', 'IN REVIEW')], default='in review', max_length=20),
        ),
    ]
