# Generated by Django 4.0 on 2022-07-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_alter_employee_employee_id'),
        ('applicant', '0002_alter_applicant_comment_alter_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_department', to='hrms.department'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_designation', to='hrms.designation'),
        ),
    ]
