# Generated by Django 4.0.7 on 2022-12-22 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_alter_applicant_cv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ('updated_at',)},
        ),
    ]
