# Generated by Django 4.0.7 on 2022-12-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_alter_applicant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='offerletter/%Y-%m-%d'),
        ),
    ]
