# Generated by Django 4.0 on 2022-07-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_applicant_appicant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='appicant_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
