# Generated by Django 4.0.7 on 2022-12-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0006_offerletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerletter',
            options={'verbose_name': 'offer letter', 'verbose_name_plural': 'offer letter'},
        ),
        migrations.AddField(
            model_name='applicant',
            name='is_appicant',
            field=models.BooleanField(default=True),
        ),
    ]
