# Generated by Django 4.0 on 2022-07-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_applicant_email_applicant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='other_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
