# Generated by Django 4.0 on 2022-07-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_alter_applicant_other_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='appicant_id',
            new_name='applicant_id',
        ),
    ]
