# Generated by Django 4.0 on 2022-07-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0009_alter_applicant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='media/cv/%Y-%m-%d'),
        ),
    ]
