# Generated by Django 4.0 on 2022-07-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0010_alter_applicant_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('selected', 'SELECTED'), ('not selected', 'NOT SELECTED'), ('in review', 'IN REVIEW')], default='in review', max_length=20),
        ),
    ]
