# Generated by Django 4.0 on 2022-07-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0011_alter_applicant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='job_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
