# Generated by Django 4.0 on 2022-07-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0012_applicant_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='job_title',
        ),
        migrations.AddField(
            model_name='applicant',
            name='resuming_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
