# Generated by Django 4.0 on 2022-07-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0013_remove_applicant_job_title_applicant_resuming_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
