# Generated by Django 4.0 on 2022-08-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0014_applicant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='sala',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
