# Generated by Django 4.0.7 on 2023-01-02 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0014_alter_applicant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='offer_letter',
        ),
        migrations.CreateModel(
            name='ApplicantOfferLeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='offerletter/%Y-%m-%d')),
                ('appliant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_offer_letters', to='applicant.applicant')),
            ],
        ),
    ]
