# Generated by Django 4.0.7 on 2023-01-02 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0015_remove_applicant_offer_letter_applicantofferleter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantofferleter',
            old_name='appliant_id',
            new_name='appliant',
        ),
    ]
