# Generated by Django 4.0 on 2022-08-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0015_applicant_sala'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='sala',
            new_name='salary',
        ),
    ]
