# Generated by Django 4.0.7 on 2023-01-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0016_rename_appliant_id_applicantofferleter_appliant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantofferleter',
            options={'verbose_name': 'Offer Letter', 'verbose_name_plural': 'Offer Letters'},
        ),
    ]
