# Generated by Django 4.0.7 on 2023-01-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0017_alter_applicantofferleter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
